# This file was generated by GoReleaser. DO NOT EDIT.
cask "nigopdf" do
  version "0.3.0"

  on_macos do
    on_intel do
      url "https://github.com/wadoyoka/nigopdf/releases/download/v#{version}/nigopdf_#{version}_darwin_amd64.tar.gz"
      sha256 "d5f4493f536bbeef3f1a1607751af2986500258ab154767587c9f776c990f970"
    end
    on_arm do
      url "https://github.com/wadoyoka/nigopdf/releases/download/v#{version}/nigopdf_#{version}_darwin_arm64.tar.gz"
      sha256 "019894d5d3ad7745654c28f0fe919c1d394cd10d081318b90ab5b6a409f08def"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wadoyoka/nigopdf/releases/download/v#{version}/nigopdf_#{version}_linux_amd64.tar.gz"
      sha256 "1a0b559a416c56645ef82763b182e3412ec4c80ac94e09e1afa2c6f7bca91f78"
    end
    on_arm do
      url "https://github.com/wadoyoka/nigopdf/releases/download/v#{version}/nigopdf_#{version}_linux_arm64.tar.gz"
      sha256 "3a6414461782e1d27f0bc8792d363f9121b60818e90120a22cc3ea73db9f9561"
    end
  end

  name "nigopdf"
  desc "A PDF toolkit - merge and split PDF files"
  homepage "https://github.com/wadoyoka/nigopdf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nigopdf"

  # No zap stanza required

end
