# This file was generated by GoReleaser. DO NOT EDIT.
cask "nigopdf" do
  name "nigopdf"
  desc "A PDF toolkit - merge and split PDF files"
  homepage "https://github.com/wadoyoka/nigopdf"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nigopdf"

  on_macos do
    on_intel do
      url "https://github.com/wadoyoka/nigopdf/releases/download/v#{version}/nigopdf_#{version}_darwin_amd64.tar.gz"
      sha256 "cf0863a51f1a4542d168e099085dd6fa0fed699cab3ae13852bc5f5d7220a911"
    end
    on_arm do
      url "https://github.com/wadoyoka/nigopdf/releases/download/v#{version}/nigopdf_#{version}_darwin_arm64.tar.gz"
      sha256 "abb04b3252421f9d45dc56f6ab9d806a512cc4fbcef968eaab693c6881058f77"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wadoyoka/nigopdf/releases/download/v#{version}/nigopdf_#{version}_linux_amd64.tar.gz"
      sha256 "e66b682a39042f1b4b835bf25b9049e553f5acf44230ee0fe5a9ed03b781d8a1"
    end
    on_arm do
      url "https://github.com/wadoyoka/nigopdf/releases/download/v#{version}/nigopdf_#{version}_linux_arm64.tar.gz"
      sha256 "a0cbecf0e23f62200528f77a12a981390a48c23d430ae848fa333e8d0c9dc852"
    end
  end

  # No zap stanza required
end
