# This file was generated by GoReleaser. DO NOT EDIT.
cask "nigopdf" do
  name "nigopdf"
  desc "A PDF toolkit - merge and split PDF files"
  homepage "https://github.com/wadoyoka/nigopdf"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nigopdf"

  on_macos do
    on_intel do
      url "https://github.com/wadoyoka/nigopdf/releases/download/v#{version}/nigopdf_#{version}_darwin_amd64.tar.gz"
      sha256 "eeda1a769803d0d0d2b3fb1a1cd028fcd03b2acb15813baf9b282045a0fa48c1"
    end
    on_arm do
      url "https://github.com/wadoyoka/nigopdf/releases/download/v#{version}/nigopdf_#{version}_darwin_arm64.tar.gz"
      sha256 "08ea584dd457ae0537514d56ec4f11049438266db7fe3fba18c1e75c5be45c2f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wadoyoka/nigopdf/releases/download/v#{version}/nigopdf_#{version}_linux_amd64.tar.gz"
      sha256 "fdb5d49c97019fab027005eb05f74dce7b5f03d578646bd67799fcee00779d3d"
    end
    on_arm do
      url "https://github.com/wadoyoka/nigopdf/releases/download/v#{version}/nigopdf_#{version}_linux_arm64.tar.gz"
      sha256 "6c771e8fc12d4cfd6f1ca741192efbdc9871179968349a2fecc0638fc579946d"
    end
  end

  # No zap stanza required
end
