# This file was generated by GoReleaser. DO NOT EDIT.
cask "pdf-join" do
  name "pdf-join"
  desc "Merge PDF files in a directory"
  homepage "https://github.com/wadoyoka/pdf-join-go"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pdf-join"

  on_macos do
    on_intel do
      url "https://github.com/wadoyoka/pdf-join-go/releases/download/v#{version}/pdf-join-go_#{version}_darwin_amd64.tar.gz"
      sha256 "4039ecb38e866520a59fa3df9ba860eec0823a4cd9634bd3b33a893972432d71"
    end
    on_arm do
      url "https://github.com/wadoyoka/pdf-join-go/releases/download/v#{version}/pdf-join-go_#{version}_darwin_arm64.tar.gz"
      sha256 "a7bfb74f33fcf12e307e1f51a41db4848dd7fa02295e66b550301d7e90804c21"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wadoyoka/pdf-join-go/releases/download/v#{version}/pdf-join-go_#{version}_linux_amd64.tar.gz"
      sha256 "c7739700041fbd94e4a4e8971938741c8e9de235860d17418a7e43ef168b2e20"
    end
    on_arm do
      url "https://github.com/wadoyoka/pdf-join-go/releases/download/v#{version}/pdf-join-go_#{version}_linux_arm64.tar.gz"
      sha256 "3d68f43627464c1262246ebb99977ea7e799dce25bc71a9c0b372116704e0e4b"
    end
  end

  # No zap stanza required
end
