# This file was generated by GoReleaser. DO NOT EDIT.
cask "pdf-join" do
  name "pdf-join"
  desc "Merge PDF files in a directory"
  homepage "https://github.com/wadoyoka/pdf-join-go"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pdf-join"

  on_macos do
    on_intel do
      url "https://github.com/wadoyoka/pdf-join-go/releases/download/v#{version}/pdf-join-go_#{version}_darwin_amd64.tar.gz"
      sha256 "30f29fb973631f8a268a2ff02c0cbf3bdd020b75732af64d9fcd4bb67276b2d7"
    end
    on_arm do
      url "https://github.com/wadoyoka/pdf-join-go/releases/download/v#{version}/pdf-join-go_#{version}_darwin_arm64.tar.gz"
      sha256 "356b0655dcae4b3279f04e18332a7eb7fc77639bccba063cebca031190518ddd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wadoyoka/pdf-join-go/releases/download/v#{version}/pdf-join-go_#{version}_linux_amd64.tar.gz"
      sha256 "0ccbfd5f44f882920b8853122be1b999335b03c8d8a9afefceabe5dd518302be"
    end
    on_arm do
      url "https://github.com/wadoyoka/pdf-join-go/releases/download/v#{version}/pdf-join-go_#{version}_linux_arm64.tar.gz"
      sha256 "dde2fd3e05898634ae12be5e2c5b10e644f4fd83ca61c8a21e1a5dcf4a53236b"
    end
  end

  # No zap stanza required
end
