# This file was generated by GoReleaser. DO NOT EDIT.
cask "pdf-join" do
  name "pdf-join"
  desc "Merge PDF files in a directory"
  homepage "https://github.com/wadoyoka/pdf-join-go"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pdf-join"

  on_macos do
    on_intel do
      url "https://github.com/wadoyoka/pdf-join-go/releases/download/v#{version}/pdf-join-go_#{version}_darwin_amd64.tar.gz"
      sha256 "662d4398f055191324b23581d412569a58e051cd913154c182ca2b2aa63d1da2"
    end
    on_arm do
      url "https://github.com/wadoyoka/pdf-join-go/releases/download/v#{version}/pdf-join-go_#{version}_darwin_arm64.tar.gz"
      sha256 "14fd444d3a22028ce846d9e96c2e4746a6b4854e235562496ebdb44702686555"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wadoyoka/pdf-join-go/releases/download/v#{version}/pdf-join-go_#{version}_linux_amd64.tar.gz"
      sha256 "dd0672b23d4936eaaa2c0762f87af5ec4ec64ea55caa54ed3a4f1a6f4afdb068"
    end
    on_arm do
      url "https://github.com/wadoyoka/pdf-join-go/releases/download/v#{version}/pdf-join-go_#{version}_linux_arm64.tar.gz"
      sha256 "2ea3c095681752050d6d8998d20251e50845f9876dd6068ccff053c3fb0748a5"
    end
  end

  # No zap stanza required
end
